# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
exclude: "lib/"
default_stages: [commit]

repos:
  - repo: 'https://github.com/pre-commit/pre-commit-hooks'
    rev: v4.5.0
    hooks:
      - id: end-of-file-fixer
      - id: check-case-conflict
      - id: check-added-large-files
      - id: check-byte-order-marker
      - id: check-ast
      - id: check-yaml
      - id: name-tests-test
        args: ['--pytest-test-first']
      - id: requirements-txt-fixer
      - id: sort-simple-yaml
  - repo: 'https://github.com/PyCQA/flake8'
    rev: 6.1.0
    hooks:
      - id: flake8
        additional_dependencies:
          - flake8-bugbear
  - repo: 'https://github.com/psf/black'
    rev: 23.11.0
    hooks:
      - id: black
  - repo: local
    hooks:
      - id: custom
        name: custom
        entry: make
        args: ['tests']
        language: system
        pass_filenames: false
