# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.25

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /home/vladislav/.local/lib/python3.10/site-packages/cmake/data/bin/cmake

# The command to remove a file.
RM = /home/vladislav/.local/lib/python3.10/site-packages/cmake/data/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = "/home/vladislav/Рабочий стол/tr"

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = "/home/vladislav/Рабочий стол/tr/build"

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/home/vladislav/.local/lib/python3.10/site-packages/cmake/data/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/home/vladislav/.local/lib/python3.10/site-packages/cmake/data/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start "/home/vladislav/Рабочий стол/tr/build/CMakeFiles" "/home/vladislav/Рабочий стол/tr/build//CMakeFiles/progress.marks"
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start "/home/vladislav/Рабочий стол/tr/build/CMakeFiles" 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named gsl_operations

# Build rule for target.
gsl_operations: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 gsl_operations
.PHONY : gsl_operations

# fast build rule for target.
gsl_operations/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gsl_operations.dir/build.make CMakeFiles/gsl_operations.dir/build
.PHONY : gsl_operations/fast

binarize.o: binarize.cpp.o
.PHONY : binarize.o

# target to build an object file
binarize.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gsl_operations.dir/build.make CMakeFiles/gsl_operations.dir/binarize.cpp.o
.PHONY : binarize.cpp.o

binarize.i: binarize.cpp.i
.PHONY : binarize.i

# target to preprocess a source file
binarize.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gsl_operations.dir/build.make CMakeFiles/gsl_operations.dir/binarize.cpp.i
.PHONY : binarize.cpp.i

binarize.s: binarize.cpp.s
.PHONY : binarize.s

# target to generate assembly for a file
binarize.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gsl_operations.dir/build.make CMakeFiles/gsl_operations.dir/binarize.cpp.s
.PHONY : binarize.cpp.s

boxCounting.o: boxCounting.cpp.o
.PHONY : boxCounting.o

# target to build an object file
boxCounting.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gsl_operations.dir/build.make CMakeFiles/gsl_operations.dir/boxCounting.cpp.o
.PHONY : boxCounting.cpp.o

boxCounting.i: boxCounting.cpp.i
.PHONY : boxCounting.i

# target to preprocess a source file
boxCounting.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gsl_operations.dir/build.make CMakeFiles/gsl_operations.dir/boxCounting.cpp.i
.PHONY : boxCounting.cpp.i

boxCounting.s: boxCounting.cpp.s
.PHONY : boxCounting.s

# target to generate assembly for a file
boxCounting.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gsl_operations.dir/build.make CMakeFiles/gsl_operations.dir/boxCounting.cpp.s
.PHONY : boxCounting.cpp.s

calcDerivative.o: calcDerivative.cpp.o
.PHONY : calcDerivative.o

# target to build an object file
calcDerivative.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gsl_operations.dir/build.make CMakeFiles/gsl_operations.dir/calcDerivative.cpp.o
.PHONY : calcDerivative.cpp.o

calcDerivative.i: calcDerivative.cpp.i
.PHONY : calcDerivative.i

# target to preprocess a source file
calcDerivative.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gsl_operations.dir/build.make CMakeFiles/gsl_operations.dir/calcDerivative.cpp.i
.PHONY : calcDerivative.cpp.i

calcDerivative.s: calcDerivative.cpp.s
.PHONY : calcDerivative.s

# target to generate assembly for a file
calcDerivative.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gsl_operations.dir/build.make CMakeFiles/gsl_operations.dir/calcDerivative.cpp.s
.PHONY : calcDerivative.cpp.s

calc_Increase.o: calc_Increase.cpp.o
.PHONY : calc_Increase.o

# target to build an object file
calc_Increase.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gsl_operations.dir/build.make CMakeFiles/gsl_operations.dir/calc_Increase.cpp.o
.PHONY : calc_Increase.cpp.o

calc_Increase.i: calc_Increase.cpp.i
.PHONY : calc_Increase.i

# target to preprocess a source file
calc_Increase.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gsl_operations.dir/build.make CMakeFiles/gsl_operations.dir/calc_Increase.cpp.i
.PHONY : calc_Increase.cpp.i

calc_Increase.s: calc_Increase.cpp.s
.PHONY : calc_Increase.s

# target to generate assembly for a file
calc_Increase.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gsl_operations.dir/build.make CMakeFiles/gsl_operations.dir/calc_Increase.cpp.s
.PHONY : calc_Increase.cpp.s

calc_Regression.o: calc_Regression.cpp.o
.PHONY : calc_Regression.o

# target to build an object file
calc_Regression.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gsl_operations.dir/build.make CMakeFiles/gsl_operations.dir/calc_Regression.cpp.o
.PHONY : calc_Regression.cpp.o

calc_Regression.i: calc_Regression.cpp.i
.PHONY : calc_Regression.i

# target to preprocess a source file
calc_Regression.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gsl_operations.dir/build.make CMakeFiles/gsl_operations.dir/calc_Regression.cpp.i
.PHONY : calc_Regression.cpp.i

calc_Regression.s: calc_Regression.cpp.s
.PHONY : calc_Regression.s

# target to generate assembly for a file
calc_Regression.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gsl_operations.dir/build.make CMakeFiles/gsl_operations.dir/calc_Regression.cpp.s
.PHONY : calc_Regression.cpp.s

compute_derivative.o: compute_derivative.cpp.o
.PHONY : compute_derivative.o

# target to build an object file
compute_derivative.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gsl_operations.dir/build.make CMakeFiles/gsl_operations.dir/compute_derivative.cpp.o
.PHONY : compute_derivative.cpp.o

compute_derivative.i: compute_derivative.cpp.i
.PHONY : compute_derivative.i

# target to preprocess a source file
compute_derivative.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gsl_operations.dir/build.make CMakeFiles/gsl_operations.dir/compute_derivative.cpp.i
.PHONY : compute_derivative.cpp.i

compute_derivative.s: compute_derivative.cpp.s
.PHONY : compute_derivative.s

# target to generate assembly for a file
compute_derivative.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gsl_operations.dir/build.make CMakeFiles/gsl_operations.dir/compute_derivative.cpp.s
.PHONY : compute_derivative.cpp.s

compute_square.o: compute_square.cpp.o
.PHONY : compute_square.o

# target to build an object file
compute_square.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gsl_operations.dir/build.make CMakeFiles/gsl_operations.dir/compute_square.cpp.o
.PHONY : compute_square.cpp.o

compute_square.i: compute_square.cpp.i
.PHONY : compute_square.i

# target to preprocess a source file
compute_square.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gsl_operations.dir/build.make CMakeFiles/gsl_operations.dir/compute_square.cpp.i
.PHONY : compute_square.cpp.i

compute_square.s: compute_square.cpp.s
.PHONY : compute_square.s

# target to generate assembly for a file
compute_square.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gsl_operations.dir/build.make CMakeFiles/gsl_operations.dir/compute_square.cpp.s
.PHONY : compute_square.cpp.s

countUniqueMarkers.o: countUniqueMarkers.cpp.o
.PHONY : countUniqueMarkers.o

# target to build an object file
countUniqueMarkers.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gsl_operations.dir/build.make CMakeFiles/gsl_operations.dir/countUniqueMarkers.cpp.o
.PHONY : countUniqueMarkers.cpp.o

countUniqueMarkers.i: countUniqueMarkers.cpp.i
.PHONY : countUniqueMarkers.i

# target to preprocess a source file
countUniqueMarkers.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gsl_operations.dir/build.make CMakeFiles/gsl_operations.dir/countUniqueMarkers.cpp.i
.PHONY : countUniqueMarkers.cpp.i

countUniqueMarkers.s: countUniqueMarkers.cpp.s
.PHONY : countUniqueMarkers.s

# target to generate assembly for a file
countUniqueMarkers.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gsl_operations.dir/build.make CMakeFiles/gsl_operations.dir/countUniqueMarkers.cpp.s
.PHONY : countUniqueMarkers.cpp.s

hasNumber.o: hasNumber.cpp.o
.PHONY : hasNumber.o

# target to build an object file
hasNumber.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gsl_operations.dir/build.make CMakeFiles/gsl_operations.dir/hasNumber.cpp.o
.PHONY : hasNumber.cpp.o

hasNumber.i: hasNumber.cpp.i
.PHONY : hasNumber.i

# target to preprocess a source file
hasNumber.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gsl_operations.dir/build.make CMakeFiles/gsl_operations.dir/hasNumber.cpp.i
.PHONY : hasNumber.cpp.i

hasNumber.s: hasNumber.cpp.s
.PHONY : hasNumber.s

# target to generate assembly for a file
hasNumber.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gsl_operations.dir/build.make CMakeFiles/gsl_operations.dir/hasNumber.cpp.s
.PHONY : hasNumber.cpp.s

logFrom.o: logFrom.cpp.o
.PHONY : logFrom.o

# target to build an object file
logFrom.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gsl_operations.dir/build.make CMakeFiles/gsl_operations.dir/logFrom.cpp.o
.PHONY : logFrom.cpp.o

logFrom.i: logFrom.cpp.i
.PHONY : logFrom.i

# target to preprocess a source file
logFrom.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gsl_operations.dir/build.make CMakeFiles/gsl_operations.dir/logFrom.cpp.i
.PHONY : logFrom.cpp.i

logFrom.s: logFrom.cpp.s
.PHONY : logFrom.s

# target to generate assembly for a file
logFrom.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gsl_operations.dir/build.make CMakeFiles/gsl_operations.dir/logFrom.cpp.s
.PHONY : logFrom.cpp.s

main.o: main.cpp.o
.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gsl_operations.dir/build.make CMakeFiles/gsl_operations.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i
.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gsl_operations.dir/build.make CMakeFiles/gsl_operations.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s
.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gsl_operations.dir/build.make CMakeFiles/gsl_operations.dir/main.cpp.s
.PHONY : main.cpp.s

markArea.o: markArea.cpp.o
.PHONY : markArea.o

# target to build an object file
markArea.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gsl_operations.dir/build.make CMakeFiles/gsl_operations.dir/markArea.cpp.o
.PHONY : markArea.cpp.o

markArea.i: markArea.cpp.i
.PHONY : markArea.i

# target to preprocess a source file
markArea.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gsl_operations.dir/build.make CMakeFiles/gsl_operations.dir/markArea.cpp.i
.PHONY : markArea.cpp.i

markArea.s: markArea.cpp.s
.PHONY : markArea.s

# target to generate assembly for a file
markArea.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gsl_operations.dir/build.make CMakeFiles/gsl_operations.dir/markArea.cpp.s
.PHONY : markArea.cpp.s

markInnerOnes.o: markInnerOnes.cpp.o
.PHONY : markInnerOnes.o

# target to build an object file
markInnerOnes.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gsl_operations.dir/build.make CMakeFiles/gsl_operations.dir/markInnerOnes.cpp.o
.PHONY : markInnerOnes.cpp.o

markInnerOnes.i: markInnerOnes.cpp.i
.PHONY : markInnerOnes.i

# target to preprocess a source file
markInnerOnes.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gsl_operations.dir/build.make CMakeFiles/gsl_operations.dir/markInnerOnes.cpp.i
.PHONY : markInnerOnes.cpp.i

markInnerOnes.s: markInnerOnes.cpp.s
.PHONY : markInnerOnes.s

# target to generate assembly for a file
markInnerOnes.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gsl_operations.dir/build.make CMakeFiles/gsl_operations.dir/markInnerOnes.cpp.s
.PHONY : markInnerOnes.cpp.s

markIsolatedZeros.o: markIsolatedZeros.cpp.o
.PHONY : markIsolatedZeros.o

# target to build an object file
markIsolatedZeros.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gsl_operations.dir/build.make CMakeFiles/gsl_operations.dir/markIsolatedZeros.cpp.o
.PHONY : markIsolatedZeros.cpp.o

markIsolatedZeros.i: markIsolatedZeros.cpp.i
.PHONY : markIsolatedZeros.i

# target to preprocess a source file
markIsolatedZeros.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gsl_operations.dir/build.make CMakeFiles/gsl_operations.dir/markIsolatedZeros.cpp.i
.PHONY : markIsolatedZeros.cpp.i

markIsolatedZeros.s: markIsolatedZeros.cpp.s
.PHONY : markIsolatedZeros.s

# target to generate assembly for a file
markIsolatedZeros.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gsl_operations.dir/build.make CMakeFiles/gsl_operations.dir/markIsolatedZeros.cpp.s
.PHONY : markIsolatedZeros.cpp.s

memory_free.o: memory_free.cpp.o
.PHONY : memory_free.o

# target to build an object file
memory_free.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gsl_operations.dir/build.make CMakeFiles/gsl_operations.dir/memory_free.cpp.o
.PHONY : memory_free.cpp.o

memory_free.i: memory_free.cpp.i
.PHONY : memory_free.i

# target to preprocess a source file
memory_free.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gsl_operations.dir/build.make CMakeFiles/gsl_operations.dir/memory_free.cpp.i
.PHONY : memory_free.cpp.i

memory_free.s: memory_free.cpp.s
.PHONY : memory_free.s

# target to generate assembly for a file
memory_free.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gsl_operations.dir/build.make CMakeFiles/gsl_operations.dir/memory_free.cpp.s
.PHONY : memory_free.cpp.s

slide_box_counting.o: slide_box_counting.cpp.o
.PHONY : slide_box_counting.o

# target to build an object file
slide_box_counting.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gsl_operations.dir/build.make CMakeFiles/gsl_operations.dir/slide_box_counting.cpp.o
.PHONY : slide_box_counting.cpp.o

slide_box_counting.i: slide_box_counting.cpp.i
.PHONY : slide_box_counting.i

# target to preprocess a source file
slide_box_counting.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gsl_operations.dir/build.make CMakeFiles/gsl_operations.dir/slide_box_counting.cpp.i
.PHONY : slide_box_counting.cpp.i

slide_box_counting.s: slide_box_counting.cpp.s
.PHONY : slide_box_counting.s

# target to generate assembly for a file
slide_box_counting.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gsl_operations.dir/build.make CMakeFiles/gsl_operations.dir/slide_box_counting.cpp.s
.PHONY : slide_box_counting.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... gsl_operations"
	@echo "... binarize.o"
	@echo "... binarize.i"
	@echo "... binarize.s"
	@echo "... boxCounting.o"
	@echo "... boxCounting.i"
	@echo "... boxCounting.s"
	@echo "... calcDerivative.o"
	@echo "... calcDerivative.i"
	@echo "... calcDerivative.s"
	@echo "... calc_Increase.o"
	@echo "... calc_Increase.i"
	@echo "... calc_Increase.s"
	@echo "... calc_Regression.o"
	@echo "... calc_Regression.i"
	@echo "... calc_Regression.s"
	@echo "... compute_derivative.o"
	@echo "... compute_derivative.i"
	@echo "... compute_derivative.s"
	@echo "... compute_square.o"
	@echo "... compute_square.i"
	@echo "... compute_square.s"
	@echo "... countUniqueMarkers.o"
	@echo "... countUniqueMarkers.i"
	@echo "... countUniqueMarkers.s"
	@echo "... hasNumber.o"
	@echo "... hasNumber.i"
	@echo "... hasNumber.s"
	@echo "... logFrom.o"
	@echo "... logFrom.i"
	@echo "... logFrom.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... markArea.o"
	@echo "... markArea.i"
	@echo "... markArea.s"
	@echo "... markInnerOnes.o"
	@echo "... markInnerOnes.i"
	@echo "... markInnerOnes.s"
	@echo "... markIsolatedZeros.o"
	@echo "... markIsolatedZeros.i"
	@echo "... markIsolatedZeros.s"
	@echo "... memory_free.o"
	@echo "... memory_free.i"
	@echo "... memory_free.s"
	@echo "... slide_box_counting.o"
	@echo "... slide_box_counting.i"
	@echo "... slide_box_counting.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

